"""export table

Revision ID: 10f4ac7625f0
Revises: 2f2481b79a93
Create Date: 2026-09-20 22:54:24.481592
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '10f4ac7625f0'
down_revision: str | None = '2f2481b79a93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('blockers', sa.Integer(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export')
    # ### end Alembic commands ###
