"""event log

Revision ID: 57f4a1b45d55
Revises: c3a71b9f2d40
Create Date: 2026-09-26 22:30:01.791265
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '57f4a1b45d55'
down_revision: str | None = 'c3a71b9f2d40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # The log is only ever read newest-first, and grows without bound until
    # something prunes it. Without this the admin page table-scans it.
    op.create_index('ix_event_at', 'event', [sa.text('at DESC')])
    op.create_index('ix_event_category_at', 'event', ['category', sa.text('at DESC')])


def downgrade() -> None:
    op.drop_index('ix_event_category_at', table_name='event')
    op.drop_index('ix_event_at', table_name='event')
    op.drop_table('event')
