"""export unchecked count

Revision ID: 839cd46850f9
Revises: 10f4ac7625f0
Create Date: 2026-09-20 23:06:31.958385
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '839cd46850f9'
down_revision: str | None = '10f4ac7625f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate the column; they recorded blockers only.
    op.add_column(
        "export",
        sa.Column("unchecked", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("export", "unchecked", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'unchecked')
    # ### end Alembic commands ###
