"""evidence desk

Revision ID: 8acd207f2637
Revises: c411d72d040c
Create Date: 2026-10-03 21:23:33.659430
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8acd207f2637'
down_revision: str | None = 'c411d72d040c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# JSONB on PostgreSQL, plain JSON on SQLite. Spelled out rather than imported:
# a migration must keep meaning what it meant when it ran.
Json = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('from_set', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_set',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('questions', Json, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('evidence_question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', Json, nullable=True),
    sa.Column('multiple', sa.Boolean(), nullable=False),
    sa.Column('commands', Json, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evidence_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'key')
    )
    op.create_index(op.f('ix_evidence_question_case_id'), 'evidence_question', ['case_id'], unique=False)
    op.create_table('evidence_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('sources', sa.Integer(), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('stats', Json, nullable=True),
    sa.Column('errors', Json, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evidence_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_run_case_id'), 'evidence_run', ['case_id'], unique=False)
    op.create_table('evidence_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('parser', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('language_set', sa.Boolean(), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('sender_name', sa.String(length=300), nullable=True),
    sa.Column('sender_domain', sa.String(length=300), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('meta', Json, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['evidence_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['evidence_source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_source_case_id'), 'evidence_source', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_sender_domain'), 'evidence_source', ['sender_domain'], unique=False)
    op.create_table('evidence_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('thumb_uri', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['evidence_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sha256')
    )
    op.create_index(op.f('ix_evidence_asset_case_id'), 'evidence_asset', ['case_id'], unique=False)
    op.create_table('evidence_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_from', sa.Integer(), nullable=False),
    sa.Column('char_to', sa.Integer(), nullable=False),
    sa.Column('page_from', sa.Integer(), nullable=True),
    sa.Column('page_to', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('meta', Json, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'seq')
    )
    op.create_index(op.f('ix_evidence_chunk_source_id'), 'evidence_chunk', ['source_id'], unique=False)
    op.create_table('evidence_candidate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_norm', sa.Text(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('char_from', sa.Integer(), nullable=True),
    sa.Column('char_to', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('ranked_of', sa.Integer(), nullable=True),
    sa.Column('found_by', sa.Text(), nullable=True),
    sa.Column('occurrences', Json, nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['evidence_chunk.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['evidence_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evidence_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'value_norm')
    )
    op.create_index(op.f('ix_evidence_candidate_question_id'), 'evidence_candidate', ['question_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-added. Autogenerate does not propose these because the models do not
    # declare them, and the models do not declare them because a DESC index is
    # not expressible there — the same reason the event and house_style indexes
    # were written by hand in their own migrations.
    #
    # The runs list is "this run and the ones before it", newest first, which is
    # the only way `evidence_run` is ever read.
    op.create_index(
        op.f('ix_evidence_run_case_at'),
        'evidence_run',
        ['case_id', sa.literal_column('created_at DESC')],
        unique=False,
    )
    # The review surface asks one question of this table: what is still pending
    # for this question. Accepted and dismissed rows accumulate run after run and
    # would otherwise be scanned past every time.
    op.create_index(
        op.f('ix_evidence_candidate_pending'),
        'evidence_candidate',
        ['question_id', 'status'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_evidence_candidate_pending'), table_name='evidence_candidate')
    op.drop_index(op.f('ix_evidence_run_case_at'), table_name='evidence_run')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_candidate_question_id'), table_name='evidence_candidate')
    op.drop_table('evidence_candidate')
    op.drop_index(op.f('ix_evidence_chunk_source_id'), table_name='evidence_chunk')
    op.drop_table('evidence_chunk')
    op.drop_index(op.f('ix_evidence_asset_case_id'), table_name='evidence_asset')
    op.drop_table('evidence_asset')
    op.drop_index(op.f('ix_evidence_source_sender_domain'), table_name='evidence_source')
    op.drop_index(op.f('ix_evidence_source_case_id'), table_name='evidence_source')
    op.drop_table('evidence_source')
    op.drop_index(op.f('ix_evidence_run_case_id'), table_name='evidence_run')
    op.drop_table('evidence_run')
    op.drop_index(op.f('ix_evidence_question_case_id'), table_name='evidence_question')
    op.drop_table('evidence_question')
    op.drop_table('question_set')
    op.drop_table('evidence_case')
    # ### end Alembic commands ###
