"""doc type draft

Revision ID: f6e2be5dffb1
Revises: 2ab69f508b22
Create Date: 2026-09-21 19:04:59.363538
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f6e2be5dffb1'
down_revision: str | None = '2ab69f508b22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_type_draft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_type_key', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('based_on', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_type_draft_doc_type_key'), 'doc_type_draft', ['doc_type_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_type_draft_doc_type_key'), table_name='doc_type_draft')
    op.drop_table('doc_type_draft')
    # ### end Alembic commands ###
